name: Springboot App of Gifts


on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    strategy:
      matrix:
        retries: [ 1 ]
    name  : build and deploy springboot app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Up Jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          tasks: clean test

      - name: Build the application code
        run: |
          ./gradlew clean
          ./gradlew test

      - name: clear docker cache
        run: docker builder prune --force

      - name: Clean Up Workspace
        run: |
          rm -rf /tmp/buildkit-mount*

      - name: Build Docker Image
        uses: docker/setup-buildx-action@v1
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME}}/infraops:latest

      - name: Login to dockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: push to dockerhub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME}}/infraops:latest
